In [5]:
import pandas as pd
import seaborn as sb
df=pd.read_csv(r"C:\Users\K.PRABHU\Downloads\dsp lab\claim_insurance.csv")

In [6]:
df.head()

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,transimission_type
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
1,10,9,35,11,27003,3,10,1,10,2,...,1,1,1,1,1,1,1,4,0,NaN
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,1,0,0,0,1,0,0,NaN
4,4,5,56,4,5410,2,6,1,4,2,...,1,1,1,0,0,1,1,5,0,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 39 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   subscription_length               58592 non-null  int64
 1   vehicle_age                       58592 non-null  int64
 2   customer_age                      58592 non-null  int64
 3   region_code                       58592 non-null  int64
 4   region_density                    58592 non-null  int64
 5   segment                           58592 non-null  int64
 6   model                             58592 non-null  int64
 7   fuel_type                         58592 non-null  int64
 8   engine_type                       58592 non-null  int64
 9   airbags                           58592 non-null  int64
 10  is_esc                            58592 non-null  int64
 11  is_adjustable_steering            58592 non-null  int64
 12  is_tpms                           58592 non-null  int64
 13  is_parking_sensors                58592 non-null  int64
 14  is_parking_camera                 58592 non-null  int64
 15  rear_brakes_type                  0 non-null      float64
 16  displacement                      58592 non-null  int64
 17  cylinder                          58592 non-null  int64
 18  transmission_type                 58592 non-null  int64
 19  steering_type                     0 non-null      float64
 20  turning_radius                    58592 non-null  int64
 21  length                            58592 non-null  int64
 22  width                             58592 non-null  int64
 23  gross_weight                      58592 non-null  int64
 24  is_front_fog_lights               58592 non-null  int64
 25  is_rear_window_wiper              58592 non-null  int64
 26  is_rear_window_washer             58592 non-null  int64
 27  is_rear_window_defogger           58592 non-null  int64
 28  is_brake_assist                   58592 non-null  int64
 29  is_power_door_locks               58592 non-null  int64
 30  is_central_locking                58592 non-null  int64
 31  is_power_steering                 58592 non-null  int64
 32  is_driver_seat_height_adjustable  58592 non-null  int64
 33  is_day_night_rear_view_mirror     58592 non-null  int64
 34  is_ecw                            58592 non-null  int64
 35  is_speed_alert                    58592 non-null  int64
 36  ncap_rating                       58592 non-null  int64
 37  claim_status                      58592 non-null  int64
 38  transimission_type                0 non-null      float64
dtypes: float64(3), int64(36)
memory usage: 17.4 MB

In [8]:
X=df.drop("claim_status",axis=1)
Y=df["claim_status"]

In [9]:
X

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,transimission_type
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,1,0,1,1,3,NaN
1,10,9,35,11,27003,3,10,1,10,2,...,0,1,1,1,1,1,1,1,4,NaN
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,1,0,1,1,3,NaN
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,0,1,0,0,0,1,0,NaN
4,4,5,56,4,5410,2,6,1,4,2,...,0,1,1,1,0,0,1,1,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,8,13,48,17,34738,2,7,2,8,2,...,1,1,1,1,1,1,1,1,2,NaN
58588,3,11,37,15,4076,4,5,1,3,6,...,1,1,1,1,1,0,1,1,3,NaN
58589,8,11,35,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,1,2,NaN
58590,8,18,44,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,1,2,NaN
58591,8,2,49,3,34791,2,7,2,8,2,...,1,1,1,1,1,1,1,1,2,NaN

In [10]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
58587    0
58588    0
58589    0
58590    0
58591    0
Name: claim_status, Length: 58592, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['rear_brakes_type']=encoder.fit_transform(df['rear_brakes_type'])
df['steering_type']=encoder.fit_transform(df['steering_type'])
df['transmission_type']=encoder.fit_transform(df['transmission_type'])

In [12]:
X=df.drop(columns=['rear_brakes_type','steering_type','transimission_type'])

In [13]:
X.dtypes

subscription_length                 int64
vehicle_age                         int64
customer_age                        int64
region_code                         int64
region_density                      int64
segment                             int64
model                               int64
fuel_type                           int64
engine_type                         int64
airbags                             int64
is_esc                              int64
is_adjustable_steering              int64
is_tpms                             int64
is_parking_sensors                  int64
is_parking_camera                   int64
displacement                        int64
cylinder                            int64
transmission_type                   int64
turning_radius                      int64
length                              int64
width                               int64
gross_weight                        int64
is_front_fog_lights                 int64
is_rear_window_wiper                int64
is_rear_window_washer               int64
is_rear_window_defogger             int64
is_brake_assist                     int64
is_power_door_locks                 int64
is_central_locking                  int64
is_power_steering                   int64
is_driver_seat_height_adjustable    int64
is_day_night_rear_view_mirror       int64
is_ecw                              int64
is_speed_alert                      int64
ncap_rating                         int64
claim_status                        int64
dtype: object

In [14]:
Y.dtypes

dtype('int64')

In [15]:
df.head()

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,transimission_type
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
1,10,9,35,11,27003,3,10,1,10,2,...,1,1,1,1,1,1,1,4,0,NaN
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,1,0,0,0,1,0,0,NaN
4,4,5,56,4,5410,2,6,1,4,2,...,1,1,1,0,0,1,1,5,0,NaN

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [17]:
import pandas as pd

df = pd.read_csv("claim_insurance.csv")

# remove extra spaces
df.columns = df.columns.str.strip()

# drop wrong column
df = df.drop(columns=['transimission_type'], errors='ignore')

In [18]:
X.dtypes

subscription_length                 int64
vehicle_age                         int64
customer_age                        int64
region_code                         int64
region_density                      int64
segment                             int64
model                               int64
fuel_type                           int64
engine_type                         int64
airbags                             int64
is_esc                              int64
is_adjustable_steering              int64
is_tpms                             int64
is_parking_sensors                  int64
is_parking_camera                   int64
displacement                        int64
cylinder                            int64
transmission_type                   int64
turning_radius                      int64
length                              int64
width                               int64
gross_weight                        int64
is_front_fog_lights                 int64
is_rear_window_wiper                int64
is_rear_window_washer               int64
is_rear_window_defogger             int64
is_brake_assist                     int64
is_power_door_locks                 int64
is_central_locking                  int64
is_power_steering                   int64
is_driver_seat_height_adjustable    int64
is_day_night_rear_view_mirror       int64
is_ecw                              int64
is_speed_alert                      int64
ncap_rating                         int64
claim_status                        int64
dtype: object

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, Y_train)
Y_pred = log_reg.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(Y_test, Y_pred))

Logistic Regression Accuracy: 1.0

c:\Users\K.PRABHU\.conda\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

df = DecisionTreeClassifier()
df.fit(X_train, Y_train)

Y_pred_df = df.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(Y_test, Y_pred_df))

Decision Tree Accuracy: 1.0

In [21]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, Y_train)

Y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(Y_test, Y_pred_rf))

Random Forest Accuracy: 1.0

In [22]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("KNN Accuracy:", accuracy_score(Y_test, Y_pred_knn))

KNN Accuracy: 0.9419745712091475

In [23]:
from sklearn.svm import SVC

svm = SVC(kernel='rbf')  

svm.fit(X_train, Y_train)

Y_pred_svm = svm.predict(X_test)

print("SVM Accuracy:", accuracy_score(Y_test, Y_pred_svm))

SVM Accuracy: 0.9363426913559177

In [24]:
print("KNN:", accuracy_score(Y_test, Y_pred_knn))
print("SVM:", accuracy_score(Y_test, Y_pred_svm))

KNN: 0.9419745712091475
SVM: 0.9363426913559177

In [33]:
# 1. Define models
log_model = LogisticRegression()
dt_model = DecisionTreeClassifier()
rf_model = RandomForestClassifier()

# 2. Train models
log_model.fit(X_train, Y_train)
dt_model.fit(X_train, Y_train)
rf_model.fit(X_train, Y_train)

# 3. Put in dictionary
models = {
    "Logistic Regression": log_model,
    "Decision Tree": dt_model,
    "Random Forest": rf_model
}
for name, model in models.items():
    model.fit(X_train, Y_train)   # Train
    
    y_pred = model.predict(X_test)  # Predict
    
    acc = accuracy_score(Y_test, Y_pred) * 100
    prec = precision_score(Y_test, Y_pred, average='macro') * 100
    rec = recall_score(Y_test, Y_pred, average='macro') * 100
    f1 = f1_score(Y_test, Y_pred, average='macro') * 100
    
    results.append([name, round(acc,2), round(prec,2), round(rec,2), round(f1,2)])

# Print results
for r in results:
    print(r)

c:\Users\K.PRABHU\.conda\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\K.PRABHU\.conda\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

['Logistic Regression', 93.63426913559178, 0.0, 0.0, 0.0]
['Decision Tree', 100.0, 100.0, 100.0, 100.0]
['Random Forest', 100.0, 100.0, 100.0, 100.0]
['Logistic Regression', 100.0, 100.0, 100.0, 100.0]
['Decision Tree', 100.0, 100.0, 100.0, 100.0]
['Random Forest', 100.0, 100.0, 100.0, 100.0]